# Server
spring.application.name=tienda

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tienda}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=${JWT_SECRET:miClaveSecretaSuperSeguraParaJWT1234567890ABCDEFGHIJ}
jwt.expiration=${JWT_EXPIRATION:86400000}