# Server
spring.application.name=tienda

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tienda}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=${JWT_SECRET:miClaveSecretaSuperSeguraParaJWT1234567890ABCDEFGHIJ}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Front-end
frontend.url=${FRONTEND_URL:http://localhost:3000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:mezka28@gmail.com}
spring.mail.password=${MAIL_PASSWORD:cjzcjznrftwgjjvb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

